# Languages
#   Create a `[X]` block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Configure the English version of the site.
[ja]
  languageCode = "ja"
  contentDir = "content/ja"  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  # title = "About Me"
  weight = 10

[en]
  languageCode = "en-us"
  contentDir = "content/en"  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  # title = "About Me"
  weight = 20

  # [[en.menu.main]]
  #   name = "Biography"
  #   url = "#about"
  #   weight = 10
  # 
  # [[en.menu.main]]
  #   name = "Experience"
  #   url = "#experience"
  #   weight = 20
  # 
  # [[en.menu.main]]
  #   name = "Publications"
  #   url = "#publications"
  #   weight = 30
  # 
  # [[en.menu.main]]
  #   name = "Projects"
  #   url = "#projects"
  #   weight = 40
  # 
  # [[en.menu.main]]
  #   name = "Posts"
  #   url = "#posts"
  #   weight = 50
  # 
  # [[en.menu.main]]
  #   name = "Contact"
  #   url = "#contact"
  #   weight = 90

# Uncomment the lines below to configure your website in a second language.
#[zh]
#  languageCode = "zh-Hans"
#  contentDir = "content/zh"
#  title = "Chinese website title..."
#  [zh.params]
#    description = "Site description in Chinese..."
#  [[zh.menu.main]]
#    name = "Wo"
#    url = "#about"
#    weight = 1
